/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_AUDIO_FILES           21
#define MMAP_AUDIO_CHECKSUM        0x4ED9

enum MMAP_AUDIO_LISTS {
    MMAP_AUDIO_0_OGG = 0,        /*!< 0.ogg */
    MMAP_AUDIO_1_OGG = 1,        /*!< 1.ogg */
    MMAP_AUDIO_2_OGG = 2,        /*!< 2.ogg */
    MMAP_AUDIO_3_OGG = 3,        /*!< 3.ogg */
    MMAP_AUDIO_4_OGG = 4,        /*!< 4.ogg */
    MMAP_AUDIO_5_OGG = 5,        /*!< 5.ogg */
    MMAP_AUDIO_6_OGG = 6,        /*!< 6.ogg */
    MMAP_AUDIO_7_OGG = 7,        /*!< 7.ogg */
    MMAP_AUDIO_8_OGG = 8,        /*!< 8.ogg */
    MMAP_AUDIO_9_OGG = 9,        /*!< 9.ogg */
    MMAP_AUDIO_ACTIVATION_OGG = 10,        /*!< activation.ogg */
    MMAP_AUDIO_ERR_PIN_OGG = 11,        /*!< err_pin.ogg */
    MMAP_AUDIO_ERR_REG_OGG = 12,        /*!< err_reg.ogg */
    MMAP_AUDIO_EXCLAMATION_OGG = 13,        /*!< exclamation.ogg */
    MMAP_AUDIO_LOW_BATTERY_OGG = 14,        /*!< low_battery.ogg */
    MMAP_AUDIO_POPUP_OGG = 15,        /*!< popup.ogg */
    MMAP_AUDIO_SUCCESS_OGG = 16,        /*!< success.ogg */
    MMAP_AUDIO_UPGRADE_OGG = 17,        /*!< upgrade.ogg */
    MMAP_AUDIO_VIBRATION_OGG = 18,        /*!< vibration.ogg */
    MMAP_AUDIO_WELCOME_OGG = 19,        /*!< welcome.ogg */
    MMAP_AUDIO_WIFICONFIG_OGG = 20,        /*!< wificonfig.ogg */
};
