/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_IMAGE_FILES           9
#define MMAP_IMAGE_CHECKSUM        0x8B6C

enum MMAP_IMAGE_LISTS {
    MMAP_IMAGE_ANGER_GIF = 0,        /*!< anger.gif */
    MMAP_IMAGE_DISDAIN_GIF = 1,        /*!< disdain.gif */
    MMAP_IMAGE_EXCITED_GIF = 2,        /*!< excited.gif */
    MMAP_IMAGE_EYES_FAST_GIF = 3,        /*!< eyes_fast.gif */
    MMAP_IMAGE_EYES_SLOW_GIF = 4,        /*!< eyes_slow.gif */
    MMAP_IMAGE_FEAR_GIF = 5,        /*!< fear.gif */
    MMAP_IMAGE_LEFT_GIF = 6,        /*!< left.gif */
    MMAP_IMAGE_RIGHT_GIF = 7,        /*!< right.gif */
    MMAP_IMAGE_SAD_GIF = 8,        /*!< sad.gif */
};
